{
 "title": "Ecommers - Observabilidad",
 "tags": [ "ecommers" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "container", "label": "Servicio (contenedor)", "query": "label_values(container)" },
   { "name": "level", "label": "Nivel", "query": "label_values(level)" }
  ]
 },
 "panels": [
  {
   "title": "Errores (rango seleccionado)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({level=\"ERROR\", container=~\"$container\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Volumen de logs por nivel",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({container=~\"$container\"} [$__auto]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{container=~\"$container\", level=~\"$level\"}"
    }
   ]
  }
 ]
}